# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: affac52989f986d634f413f6c3313e9870849a16532e88e78dd8d75d107880512b2509e15df874a39055fe9f8afd0fcf4c5f7fd57775ae2984b159652a61a4e7

test:
  secret_key_base: 2f49bb247c2c37abe46bd9c4108598f1eb4027e72eace1ccdce460ee5901693b88db1964567e03a04b00bae712a7ac0aa983efc36bdfcdf58723bd22c8b6d55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
